# Generated by Django 3.1.7 on 2021-06-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuser',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='아이디')),
                ('user_name', models.CharField(max_length=255, verbose_name='이름')),
                ('cafe_name', models.CharField(max_length=255, verbose_name='카페이름')),
                ('user_email', models.CharField(max_length=255, verbose_name='이메일')),
                ('password', models.CharField(max_length=255, verbose_name='비밀번호')),
                ('register_date', models.DateField(auto_now_add=True, verbose_name='가입날짜')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자',
                'db_table': 'fuser',
            },
        ),
    ]
