# Generated by Django 3.1.7 on 2021-05-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuser',
            name='user_id',
            field=models.CharField(max_length=32, verbose_name='아이디'),
        ),
    ]
