# Generated by Django 3.1.7 on 2021-05-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0002_auto_20210509_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fuser',
            options={'verbose_name': '사용자', 'verbose_name_plural': '사용자'},
        ),
        migrations.AddField(
            model_name='fuser',
            name='user_email',
            field=models.CharField(default='undefine@example.com', max_length=64, verbose_name='이메일'),
            preserve_default=False,
        ),
    ]
