# Generated by Django 3.1.7 on 2021-05-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0003_auto_20210509_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuser',
            name='user_name',
            field=models.CharField(default='cafe_name', max_length=32, verbose_name='카페이름'),
            preserve_default=False,
        ),
    ]
