# Generated by Django 3.1.7 on 2021-05-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0005_auto_20210523_2250'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fuser',
            table='fuser',
        ),
    ]
