# Generated by Django 3.1.7 on 2021-05-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuser', '0009_auto_20210527_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuser',
            name='cafe_name',
            field=models.CharField(default='카페이름', max_length=255, verbose_name='카페이름'),
            preserve_default=False,
        ),
    ]
