# Generated by Django 3.1.7 on 2021-05-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_name', models.CharField(max_length=64, verbose_name='카페')),
                ('cnt_stamp', models.IntegerField(verbose_name='쿠폰개수')),
                ('cafe_intro', models.CharField(max_length=300, verbose_name='카페소개')),
            ],
            options={
                'verbose_name': '등록 카페',
                'verbose_name_plural': '등록 카페',
                'db_table': 'manager',
            },
        ),
    ]
