# Generated by Django 3.1.7 on 2021-05-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='cafe_intro',
        ),
        migrations.AddField(
            model_name='manager',
            name='cafe_explain',
            field=models.CharField(default='explain cafe', max_length=400, verbose_name='카페소개'),
            preserve_default=False,
        ),
    ]
