# Generated by Django 3.1.7 on 2021-05-23 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20210517_1545'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='manager',
            table='management',
        ),
    ]
