# Generated by Django 3.1.7 on 2021-05-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20210523_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='id',
        ),
        migrations.AlterField(
            model_name='manager',
            name='cafe_name',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='카페'),
        ),
    ]
