# Generated by Django 3.1.7 on 2021-05-27 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20210524_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='cnt_stamp',
            new_name='cafe_stamp',
        ),
    ]
