# Generated by Django 3.2.3 on 2021-05-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('birth', models.CharField(max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
