# Generated by Django 3.1.7 on 2021-05-25 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20210524_1612'),
        ('account', '0004_auto_20210523_2300'),
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer', verbose_name='유저 이름'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.manager', verbose_name='카페 이름'),
        ),
    ]
