# Generated by Django 3.1.7 on 2021-05-28 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210523_2300'),
        ('coupon', '0003_auto_20210525_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='id',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='customer',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='account.customer', verbose_name='유저 이름'),
        ),
    ]
