# Generated by Django 3.1.7 on 2021-05-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_auto_20210528_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='avail',
            field=models.PositiveIntegerField(default='0', verbose_name='보유쿠폰'),
        ),
    ]
